<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latestmajor</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.9" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.9" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.9" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.9" />
      <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.9" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Bootstrap\Steps\Core\" />
      <Folder Include="Configuration\" />
      <Folder Include="Licensing\Internal\" />
      <Folder Include="Logging\Internal\" />
      <Folder Include="ResourceProvider\Materializer\Converter\" />
      <Folder Include="ResourceProvider\Materializer\Deserializer\" />
      <Folder Include="ResourceProvider\Materializer\Serializer\" />
      <Folder Include="ResourceProvider\Provider\" />
      <Folder Include="Security\" />
      <Folder Include="Utilities\" />
    </ItemGroup>

</Project>
